### PR TITLE
fix: url-encode the search query

### LINKED ISSUE #277: Url-encode searchQuery
> 
> 
> @Magos I don't think this is ready for testing. When searching for a name with & in it, I get almost all of the processes as search result. image

This part is a front-end issue, where the front end sends the parameters 
`?page=1&items=15&q=t&qa=&orderBy=modified`
but should send the parameters 
`?page=1&items=15&q=t%26qa=&orderBy=modified`
and the back-end treats "qa" as a query parameter it doesn't recognize. 
@SjoenH Could you add an urlencode step here?

_Originally posted by @Magos in https://github.com/equinor/MAD-VSM-WEB/issues/225#issuecomment-956157182_

### PR DESCRIPTION
**Pull request by SjoenH**
Search-query needs to be url-encoded for the fetch-request to be parsed correctly. Considering
special characters...

fix #277

### CODE REVIEW

**Review by dansvend — APPROVED** [review]
LGTM💪

File: utils/createUrlParams.ts [hunk 1]
```diff
@@ -3,13 +3,21 @@
  * @param params
  */
 export function createUrlParams(params: {
-  [x: string]: string | string[] | number | boolean;
+  [x: string]: string | number | boolean;
```
Comment (martabenthem) [inline utils/createUrlParams.ts:6]: Would this work when we also have `labels ` to pass as a parameter?

**Review by martabenthem — COMMENTED** [review]
Looks good! Just thinking that I will have to adapt this to also deal with string arrays, when we start passing labels as a request parameter.

File: utils/createUrlParams.ts (hunk 1 above)
Comment (Magos) [reply utils/createUrlParams.ts:6]: My expectation was that you would pass multiple labels as e.g. `rl=12&rl=42` - multiple instances of the parameter name, which is how Postman and forms seem to construct such collection parameters usually. That's why I made the labels and users params two letter names.

Comment (SjoenH) [reply utils/createUrlParams.ts:6]: This is a valid point. But my concern is not about the input type, but of line 10 here.

I'm not sure if it would work, but we probably could remove this method altogether since the format the APIs requesting looks like the same as our URL. 

Let's take a look at it when implementing labels.

Comment (martabenthem) [reply utils/createUrlParams.ts:6]: Sounds good!
