### PR TITLE
fix: Add link prompt visual bug

### LINKED ISSUE #419: Add link prompt visual bug
**Describe the bug**
The "Add link"-prompt displays other content below.

**To Reproduce**
Add a link to a card that includes time and role fields.

**Expected behavior**
The "Add link"-prompt is the only thing that should be shown when adding a link.

**Screenshots**
Uten navn

**Additional context**
Introduced with issue #175

### PR DESCRIPTION
**Pull request by ofredstie**
Fixes issue with URLPrompt only partially cover QIPSection component.

Closes #419

### CODE REVIEW

File: components/MarkdownEditor.tsx [hunk 1]
```diff
@@ -72,18 +73,7 @@ export default function MarkdownEditor(props: {
...
-          ></path>
-        </svg>
+        <Icon data={link} size={16} />
```
Comment (dansvend) [inline components/MarkdownEditor.tsx:76]: Please use `EQUINOR_PROMINENT` from `colors.ts`. Also there padding on the bottom of the icon is clipped.

File: components/MarkdownEditor.tsx [hunk 2]
```diff
@@ -26,6 +26,7 @@ export default function MarkdownEditor(props: {
   });
   // The "text"-state is used for displaying the changing text instantly
   const [text, setText] = useState(defaultText);
+  Icon.add({ link });
```
Comment (dansvend) [inline components/MarkdownEditor.tsx:29]: This can be called outside of the function since it only needs to be done once.

**Review by dansvend — CHANGES_REQUESTED** [review]

File: components/MarkdownEditor.tsx (hunk 2 above)
Comment (ofredstie) [reply components/MarkdownEditor.tsx:29]: ok

File: components/MarkdownEditor.tsx (hunk 1 above)
Comment (ofredstie) [reply components/MarkdownEditor.tsx:76]: I think that it might be the MDEditor Toolbar that is clipping it 🤔

Comment (ofredstie) [reply components/MarkdownEditor.tsx]: image

Comment (dansvend) [reply components/MarkdownEditor.tsx]: Try to add some css to fix the clipping. For example:
```CSS
.w-md-editor-toolbar > button {
  height: Xpx
}
```

File: components/MarkdownEditor.tsx [hunk 3]
```diff
@@ -72,18 +76,11 @@ export default function MarkdownEditor(props: {
...
-          ></path>
-        </svg>
+        <Icon
+          data={link}
+          color={colors.EQUINOR_PROMINENT}
+          style={{ width: 12, height: 12 }}
```
Comment (dansvend) [inline components/MarkdownEditor.tsx:82]: This makes the button too smal in my opinion. Try the CSS in the other comment and remove the style property to use the default icon size.

File: components/MarkdownEditor.tsx [hunk 4]
```diff
@@ -152,7 +149,9 @@ export default function MarkdownEditor(props: {
               },
             }}
             style={{
-              border: editMode ? "2px solid #007079" : "1px solid #ECECEC",
+              border: editMode
+                ? "2px solid " + colors.EQUINOR_PROMINENT
+                : "1px solid " + colors.EQUINOR_DISABLED,
```
Comment (dansvend) [inline components/MarkdownEditor.tsx:154]: Please use [Template literals (Template strings)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) when concatenating strings and variables 🙌

**Review by dansvend — CHANGES_REQUESTED** [review]

File: components/MarkdownEditor.tsx (hunk 1 above)
Comment (ofredstie) [reply components/MarkdownEditor.tsx]: It worked 👍 (24px)

File: components/MarkdownEditor.tsx (hunk 3 above)
Comment (ofredstie) [reply components/MarkdownEditor.tsx]: Removed

File: components/MarkdownEditor.tsx (hunk 4 above)
Comment (ofredstie) [reply components/MarkdownEditor.tsx]: Fixed

File: components/MarkdownEditor.tsx [hunk 5]
```diff
@@ -120,6 +113,9 @@ export default function MarkdownEditor(props: {
               background-color: rgb(247, 247, 247);
               color: #3d3d3d;
             }
+            .w-md-editor-toolbar li > button {
+              height: 24px;
+            }
```
Comment (dansvend) [inline components/MarkdownEditor.tsx:118]: Since there are built in buttons for the MDEditor which we might add at a later point I think we should select the specific button we are using now. This should work:

```CSS
.w-md-editor-toolbar button[data-name="link"] {
    height: 24px;
}
```

**Review by dansvend — CHANGES_REQUESTED** [review]

File: components/MarkdownEditor.tsx (hunk 5 above)
Comment (ofredstie) [reply components/MarkdownEditor.tsx]: Fixed

**Review by dansvend — APPROVED** [review]
Looks good 👌
